# SITE CONFIGURATION
title: Hey there. I am Ashwin Padmanabhan! # your site title
author: GitHub User # You :P
description: > # Meta description of Homepage
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://padmanabhanashwin.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Ashwin Padmanabhan
  links:
    #- https://twitter.com/BenBalter
    - https://www.facebook.com/ashwin.padmanabhan.7
    - https://www.linkedin.com/in/ashwin-padmanabhan-03951829/
   # - https://plus.google.com/+BenBalter
    - https://github.com/PadmanabhanAshwin
    #- https://keybase.io/benbalter

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  Operations Research/Data Science at Purdue University, West Lafayette, IN. 

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: ashwinpadmanabhan95@gmail.com # email for form submission

#twitter_username: jan_czizikow # replace with your_twitter_username or comment to remove link from footer
github_username:  PadmanabhanAshwin # replace with your_github_username or comment to remove link from footer
instagram_username: ashwinpadmanabhan # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: Ashwin # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
